### ISSUE TITLE
GUI bug when turning `steering` or `throttling` key `enabled` in config to `false`

### ISSUE THREAD

**Issue by RasyaJusticio** [RasyaJusticio/MouseSteering#2]
When I set `enabled` key in the config of `steering_config` or `throttling` config to `false`. It will show that all the values are on 50%.

![image](https://github.com/RasyaJusticio/MouseSteering/assets/125113883/b73e22f1-9b0b-45a6-bc80-c0177a13e5dd)

config.toml
```toml
screen_width = 1280
screen_height = 720

[steering_config]
enabled = false
precise_input = true
snap_input = false
snap_threshold = 0.1
edge_scaling = true
scaling_threshold = 0.8

[throttle_config]
enabled = false
precise_input = true
snap_input = true
snap_threshold = 0.1
edge_scaling = true
scaling_threshold = 0.5
```
